name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # A branch onde as novas mudanças são commitadas

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build && npm run export

      - name: Push build to another branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # A branch para onde os arquivos de build serão enviados
          FOLDER: .next # O diretório padrão onde o Next.js gera os assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token do GitHub gerado automaticamente
          MESSAGE: "Build: ({sha}) {msg}" # Mensagem do commit
